### ISSUE TITLE
Upgrade to Laravel 11

### ISSUE THREAD

**Issue by 199ocero** [mckenziearts/blade-untitledui-icons#18]
Hello @mckenziearts is there any plan to upgrade this package into Laravel 11?

**Comment by matzeschmitt** [comment]
@mckenziearts 

Hello,

First of all thanks for the package.

We also need a version compatible with Laravel 11 in the near future.

Thanks!

**Comment by mckenziearts** [comment]
New release for Laravel 11 is available #19

**Comment by matzeschmitt** [comment]
Thank you and happy Weekend!
